### ISSUE TITLE
Enable integration tests in Azure DevOps

### ISSUE THREAD

**Issue by gavinfish** [ansible-collections/ansible_collections_azure#26]
##### SUMMARY

Microsoft will take over all daily work for the Ansible Azure collection. Need to find out how to use Azure DevOps pipeline to run integration tests for a new pull request. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

CI

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by gavinfish** [comment]
Hi @mattclay ,

I have questions about the Shippable settings for this repository:

1. Does the shippable agents have any initial settings, like environment variables? 
2. I try to run the shippable.sh script on a ubuntu agent, some errors:
```
00:51 + ansible-test integration --color -v --retry-on-error shippable/azure/group1/ --coverage-check --changed --remote-terminate always --remote-stage prod --docker --python 2.7 --changed-all-target none --changed-all-mode include
00:51 The 45 minute test timeout expires in 0:44:59.374405 at 2019-12-17 03:44:11.
00:51 Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
00:51 Run command: git symbolic-ref --short HEAD
00:51 WARNING: Command "git symbolic-ref --short HEAD" returned exit status 128.
00:51 >>> Standard Error
00:51 fatal: ref HEAD is not a symbolic ref
00:51 Run command: git for-each-ref refs/heads/ --format '%(refname:strip=2)'
00:51 ERROR: Unable to auto-detect fork branch and fork point.
```
3. I also try to simply run the `ansible-test integration --allow-destructive` locally. All the tests are skipped even I create the `/home/drfish/.local/lib/python2.7/site-packages/ansible_test/config/cloud-config-azure.ini` file.
```
WARNING: Excluding tests marked "cloud/azure" which require config (see "/home/drfish/.local/lib/python2.7/site-packages/ansible_test/config/cloud-config-azure.ini.template"): azure_rm_deployment, azure_rm_dnszone, azure_rm_networkinterface, azure_rm_publicipaddress, azure_rm_securitygroup, azure_rm_storageaccount, azure_rm_subnet, azure_rm_virtualmachine, azure_rm_virtualnetwork, inventory_azure
WARNING: All targets skipped.
```

**Comment by mattclay** [comment]
@gavinfish Shippable has many [environment variables](http://docs.shippable.com/ci/env-vars/#stdEnv), although most are not used by ansible-test.

The failure you reported is due to use of the `--changed` option, which is currently supported only on Shippable. I've been planning on looking into Azure Pipelines more to see if the `--changed` option can be supported there. Until it is supported the option could be dropped, which would result in all tests being run every time.

The bigger issue is how you will manage resource groups and credentials for CI runs to enable testing of the Azure modules. That's something we may want to set up a meeting to discuss rather than trying to work it out over comments on this issue.

As for the config file when running locally, the file being referenced is a template. You will need to put a copy of the file in `test/integration/cloud-config-azure.ini` and fill in the required values.

**Comment by gavinfish** [comment]
@mattclay Thanks for sharing the knowledge here! I will set up a meeting for further discussion.
